import {empty,validate,prefCheck,previewImport,samples,getEvent,type State,type Row} from './domain';
export function apply(state:State,input:any,actor:string){const s=structuredClone(state),now=new Date().toISOString();let action='',recordId='',scope=input.sample===false?'agency':'sample',before:any=null,after:any=null;
 if(input.op==='seed'){if(s.records.some(r=>r.sample))throw Error('Samples already exist; loading never resets them.');s.records.push(...samples());action='Loaded fictional samples';}
 else if(input.op==='preferences'){s.preferences=prefCheck(input.preferences);action='Preferences updated';scope='preferences';}
 else if(input.op==='import'){if(input.mode==='replace'&&input.confirm!=='REPLACE '+scope.toUpperCase())throw Error('Type the replacement confirmation.');const p=previewImport(s,input.payload,input.mode,input.sample);s.records=p.records;for(const h of input.payload.history)if(!s.history.some(x=>x.id===h.id))s.history.push({...h,imported:true,importedAt:now});action=`${input.mode} import: ${p.added} added, ${p.skipped} identical, ${p.replaced} replaced; preferences unchanged`;}
 else if(input.op==='save'){const r:Row=structuredClone(input.record),old=s.records.find(x=>x.id===r.id);if(old&&(old.kind!==r.kind||old.sample!==r.sample))throw Error('Kind and scope cannot change.');scope=r.sample?'sample':'agency';recordId=r.id;before=old||null;
 if(r.kind==='assignment'&&old&&s.records.some(x=>x.kind==='attendance'&&x.assignment===r.id)&&['shift','volunteer'].some(k=>r[k]!==old[k]))throw Error('Assignment has attendance history; its shift and volunteer cannot be changed.');if(r.kind==='shift'&&old&&s.records.some(x=>x.kind==='attendance'&&getEvent(x,s.records)?.id===old.event)&&r.event!==old.event)throw Error('Event linkage is locked after attendance is recorded.');
 if(r.kind==='assignment'){const sh=s.records.find(x=>x.id===r.shift);if(['Invited','Assigned','Confirmed'].includes(r.status)&&(!old||old.status!==r.status||old.shift!==r.shift||old.volunteer!==r.volunteer)&&(sh?.status!=='Open'||getEvent(sh!,s.records)?.status!=='Scheduled'))throw Error('Active assignments need an open shift at a scheduled event.');if(r.status==='Confirmed'&&old?.status!=='Confirmed'){if(!input.ack)throw Error('Explicitly acknowledge volunteer acceptance.');r.confirmedAt=now;r.confirmedBy=actor;}else{r.confirmedAt=old?.confirmedAt||'';r.confirmedBy=old?.confirmedBy||'';}}
 if(r.kind==='hours'){if(!old&&r.status!=='Submitted')throw Error('Submit hours before review.');if(old?.status==='Approved'&&(r.minutes!==old.minutes||r.attendance!==old.attendance))throw Error('Reject approved hours before correcting them.');if(['Approved','Rejected'].includes(r.status)&&old?.status!==r.status){if(!input.ack)throw Error('Explicit human review is required.');r.reviewer=actor;r.reviewedAt=now;}else{r.reviewer=old?.reviewer||'';r.reviewedAt=old?.reviewedAt||'';}r.submittedAt=old?.submittedAt||now;if(r.status==='Submitted'&&old?.status!=='Submitted'){r.submittedAt=now;r.reviewer='';r.reviewedAt='';}}
 if(r.kind==='attendance'&&old&&s.records.some(h=>h.kind==='hours'&&h.attendance===r.id&&h.status==='Approved')&&['assignment','actualStart','actualEnd','status'].some(k=>r[k]!==old[k]))throw Error('Reject approved hours before correcting attendance.');
 r.updated=now;s.records=old?s.records.map(x=>x.id===r.id?r:x):[...s.records,r];
 if(['event','shift'].includes(r.kind)&&r.status==='Canceled'&&old?.status!=='Canceled'){for(const sh of s.records.filter(x=>x.kind==='shift'&&(r.kind==='event'?x.event===r.id:x.id===r.id))){if(sh.id!==r.id){s.history.push({id:crypto.randomUUID(),at:now,actor,scope,recordId:sh.id,action:'Canceled with event',before:structuredClone(sh)});sh.status='Canceled';sh.updated=now;}for(const a of s.records.filter(x=>x.kind==='assignment'&&x.shift===sh.id&&['Invited','Assigned','Confirmed'].includes(x.status))){s.history.push({id:crypto.randomUUID(),at:now,actor,scope,recordId:a.id,action:'Canceled with event or shift',before:structuredClone(a)});a.status='Canceled';a.updated=now;}}}
 after=r;action=(old?'Updated ':'Created ')+r.kind;
 }else throw Error('Unknown operation.');validate(s.records);s.history.push({id:crypto.randomUUID(),at:now,actor,scope,recordId,action,before,after});if(s.history.length>5000||JSON.stringify(s).length>1500000)throw Error('Evaluation limit reached. Export and contact administrator. No history was discarded.');return s}
export async function handle(request:Request,db:any,user:{userId:string;email:string}|null){const out=(p:any,status=200)=>Response.json(p,{status,headers:{'Cache-Control':'no-store'}});if(!user?.userId||!user.email)return out({error:'Sign in to access your private evaluator workspace.'},401);try{const found=await db.prepare('SELECT revision,payload FROM workspaces WHERE owner=?').bind(user.userId).first(),state=found?JSON.parse(found.payload):empty(),revision=found?.revision||0;if(request.method==='GET')return out({state,revision});if(request.method!=='POST')return out({error:'Method not allowed.'},405);if(request.headers.get('origin')!==new URL(request.url).origin||request.headers.get('content-type')?.split(';')[0]!=='application/json')return out({error:'Same-origin JSON request required.'},403);const raw=await request.text();if(raw.length>2000000)return out({error:'Request exceeds 2 MB.'},413);let input;try{input=JSON.parse(raw)}catch{return out({error:'Malformed JSON.'},400)}if(input.revision!==revision)return out({error:'Workspace changed. Preserve unsaved notes, close the form and Reload.'},409);const next=apply(state,input,user.userId),payload=JSON.stringify(next);const result=found?await db.prepare('UPDATE workspaces SET payload=?,revision=revision+1 WHERE owner=? AND revision=?').bind(payload,user.userId,revision).run():await db.prepare('INSERT OR IGNORE INTO workspaces (owner,revision,payload) VALUES (?,1,?)').bind(user.userId,payload).run();if(result.meta.changes!==1)return out({error:'Concurrent save. Reload before retrying.'},409);return out({state:next,revision:revision+1});}catch(e:any){return out({error:/SQLITE|D1|database/i.test(e.message)?'Storage unavailable. Input is retained; retry later.':e.message||'Save failed.'},/SQLITE|D1|database/i.test(e.message)?503:400)}}
