const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const {DatabaseSync}=require('node:sqlite');
function compile(path,requireFn){const module={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{module,exports:module.exports,require:requireFn,Response,Request,URL,crypto,console,Date,Map,Set});return module.exports;}
const rules=compile('lib/records.ts',require);const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('drizzle/0000_thankful_gwen_stacy.sql','utf8'));
const db={prepare(sql){return {bind(...args){this.args=args;return this},async all(){return {results:sqlite.prepare(sql).all(...(this.args||[]))}},run(){return {meta:sqlite.prepare(sql).run(...(this.args||[]))}}}},async batch(statements){sqlite.exec('BEGIN');try{const results=statements.map(s=>s.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const api=compile('app/api/records/route.ts',p=>p==='@/lib/database'?{database:()=>db}:rules);
const post=async body=>api.POST(new Request('https://test.local/api/records',{method:'POST',headers:{Origin:'https://test.local'},body:JSON.stringify(body)}));
const records=async()=> (await (await api.GET()).json()).records;
test('Grant workspace data lifecycle and import boundaries',async()=>{
 assert.equal((await records()).length,0);
 assert.equal((await post({op:'seed'})).status,200);
 assert.equal((await records()).length,rules.samples().length);
 assert.equal((await post({op:'seed'})).status,409);
 const requirement=(await records()).find(r=>r.kind==='requirement');
 assert.equal((await post({op:'save',record:{...requirement,status:'Complete'}})).status,400);
 assert.equal((await post({op:'save',record:{...requirement,status:'Complete',source:'javascript:alert(1)'}})).status,400);
 assert.equal((await post({op:'save',record:{...requirement,status:'Complete',source:'https://example.org/evidence'}})).status,200);
 assert.equal((await post({op:'save',record:requirement})).status,409);
 const base=rules.samples()[0];const award={...base,id:'',demo:false,title:'Agency award'};
 assert.equal((await post({op:'save',record:award})).status,200);
 assert.equal((await records()).filter(r=>!r.demo).length,1);
 assert.equal((await post({op:'save',record:{...award,kind:'requirement',status:'Open',grant:base.id}})).status,400);
 assert.equal((await post({op:'save',record:{...award,amount:-1}})).status,400);
 assert.equal((await post({op:'save',record:{...award,due:'2026-02-30'}})).status,400);
 const sampleRecords=rules.samples().slice(0,1).concat(rules.samples().slice(3,4));
 assert.equal((await post({op:'import',records:sampleRecords,demo:false})).status,200);
 const imported=(await records()).filter(r=>!r.demo&&r.title!=='Agency award');
 assert.equal(imported.find(r=>r.kind==='requirement').grant,imported.find(r=>r.kind==='grant').id);
 const before=(await records()).length;
 assert.equal((await post({op:'import',records:sampleRecords,demo:false})).status,400);
 assert.equal((await records()).length,before);
 const cross=await api.POST(new Request('https://test.local/api/records',{method:'POST',headers:{Origin:'https://other.local'},body:'{}'}));assert.equal(cross.status,403);
 const data=await (await api.GET()).json();assert.equal(data.events.length,4);
 console.log('Passed: sample isolation, create/read/update, evidence gates, unsafe URLs, stale edits, valid dates, nonnegative amounts, linked imports, duplicate rejection, origin protection, activity log.');
});

test('Dependencies, freshness, escalation, promotion and safe demo reset',async()=>{
 const all=await records();const task=all.find(r=>r.id==='sample-data-task');const report=all.find(r=>r.id==='sample-gov-report');
 assert.equal((await post({op:'save',record:{...report,status:'Complete',source:'https://example.org/report'}})).status,400);
 assert.equal((await post({op:'save',record:{...task,dependsOn:report.id}})).status,400);
 assert.equal((await post({op:'save',record:{...task,due:'2099-01-01'}})).status,400);
 assert.equal((await post({op:'save',record:{...task,status:'Complete'}})).status,200);
 assert.equal((await post({op:'save',record:{...report,status:'Complete',source:'https://example.org/report'}})).status,200);
 const freshTask=(await records()).find(r=>r.id===task.id);
 assert.equal((await post({op:'save',record:{...freshTask,status:'Open'}})).status,400);
 assert.equal(rules.financeState({}), 'UNKNOWN');
 assert.equal(rules.financeState({financialAsOf:'2020-01-01'},'2026-09-11'),'STALE');
 assert.equal((await post({op:'save',record:{...all.find(r=>r.kind==='issue'),escalationOwner:''}})).status,400);
 const lead=all.find(r=>r.kind==='opportunity');
 assert.equal((await post({op:'promote',id:lead.id})).status,200);
 assert.equal((await post({op:'promote',id:lead.id})).status,400);
 assert.ok((await records()).some(r=>r.kind==='grant'&&r.status==='Pending'));
 assert.equal((await post({op:'import',schemaVersion:99,records:[lead],demo:false})).status,400);
 const agency=JSON.stringify((await records()).filter(r=>!r.demo));
 assert.equal((await post({op:'reset',confirm:'wrong'})).status,400);
 assert.equal((await post({op:'reset',confirm:'RESET SAMPLE'})).status,200);
 assert.equal(JSON.stringify((await records()).filter(r=>!r.demo)),agency);
 assert.equal((await records()).filter(r=>r.demo).length,rules.samples().length);
});

test('Small foundation setup, custom tracking validation and export compatibility',async()=>{
 const before=await records();const agency=JSON.stringify(before.filter(r=>!r.demo));
 const tracking={...rules.emptyTracking(),funder:'Fictional foundation',awardedOn:'2026-01-01',startOn:'2026-01-01',assessment:'On track',reviewedOn:'2026-09-01',fields:[{id:'families',label:'Families reached',type:'number',value:'18',target:'30',owner:'Program staff',collect:'Count each family once monthly',due:'2026-12-01',hidden:false}],zipCodes:[{zip:'53204',families:'18',people:'40'}],payments:[{date:'2026-09-01',recipient:'Fictional supplier',purpose:'Materials',amount:'200',source:'https://example.org/receipt'}],stories:[{title:'Fictional story',text:'Synthetic outcome',photo:'https://example.org/photo'}]};
 const grant={...rules.samples()[0],id:'',title:'Small foundation test',amount:5000,spent:0,due:'2026-12-31',tracking};
 assert.equal((await post({op:'setup',record:grant,requirements:[{title:'Final report',owner:'AD',due:'2027-01-15',source:'',notes:'Families and stories'}]})).status,200);
 let all=await records();let saved=all.find(r=>r.title===grant.title);let report=all.find(r=>r.grant===saved.id);
 assert.equal(saved.tracking.fields[0].value,'18');assert.equal(report.title,'Final report');assert.equal(report.demo,true);assert.equal(JSON.stringify(all.filter(r=>!r.demo)),agency);
 const count=all.length;
 assert.equal((await post({op:'setup',record:{...grant,title:'Must rollback'},requirements:[{title:'',owner:'',due:'',notes:''}]})).status,400);assert.equal((await records()).length,count);
 assert.equal((await post({op:'save',record:{...saved,tracking:{...tracking,stories:[{title:'Bad URL',text:'',photo:'javascript:alert(1)'}]}}})).status,400);
 assert.equal((await post({op:'save',record:{...saved,tracking:{...tracking,zipCodes:[{zip:'53204',families:'-1',people:'0'}]}}})).status,400);
 assert.equal((await post({op:'save',record:{...saved,tracking:{...tracking,fields:[tracking.fields[0],tracking.fields[0]]}}})).status,400);
 assert.equal((await post({op:'save',record:{...saved,tracking:{...tracking,fields:[{...tracking.fields[0],hidden:true,value:'0'}]}}})).status,200);
 saved=(await records()).find(r=>r.id===saved.id);assert.equal(saved.tracking.fields[0].value,'0');assert.equal(saved.tracking.fields[0].hidden,true);
 assert.equal((await post({op:'save',record:{...saved,updated:'outdated'}})).status,409);
 assert.equal((await post({op:'import',schemaVersion:3,records:[saved,report],demo:false})).status,200);
 all=await records();const imported=all.find(r=>!r.demo&&r.title===grant.title);assert.equal(imported.tracking.stories[0].photo,tracking.stories[0].photo);assert.ok(all.some(r=>r.grant===imported.id&&r.title==='Final report'));
 assert.equal(rules.grantProgress({...saved,tracking:undefined},[],'2026-09-12').label,'Not reviewed');
 assert.equal(rules.grantProgress({...saved,tracking},[report],'2026-09-12').label,'On track');
 assert.equal(rules.grantProgress({...saved,tracking},[{...report,due:'2026-09-01'}],'2026-09-12').label,'Needs attention');
 assert.equal(rules.grantProgress({...saved,tracking},[report],'2026-11-01').label,'Review due');
 assert.equal(rules.grantProgress({...saved,tracking},[],'2026-12-02').label,'Needs attention');
 assert.equal(rules.grantProgress({...saved,status:'Pending',tracking},[],'2026-09-12').label,'Pending award');
});
