import {database} from '@/lib/database';
import {validate,samples,GrantRecord} from '@/lib/records';
export async function GET(){try{const db=database();const [r,a]=await Promise.all([db.prepare('SELECT payload FROM records ORDER BY updated DESC').all<{payload:string}>(),db.prepare('SELECT * FROM activity ORDER BY at DESC LIMIT 100').all()]);return Response.json({records:r.results.map(r=>JSON.parse(r.payload)),events:a.results},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return Response.json({error:'Unable to load saved records. Please retry.'},{status:503})}}
export async function POST(request:Request){try{
 const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return Response.json({error:'Request origin not allowed.'},{status:403});
 const raw=await request.text();if(raw.length>2000000)return Response.json({error:'Import is too large.'},{status:413});
 let input;try{input=JSON.parse(raw)}catch{return Response.json({error:'Invalid JSON.'},{status:400})}
 const db=database();const existing=(await db.prepare('SELECT payload FROM records').all<{payload:string}>()).results.map(r=>JSON.parse(r.payload) as GrantRecord);let items:GrantRecord[]=[];let label='';
 if(input.op==='seed'){if(existing.some(r=>r.demo))return Response.json({error:'Sample records are already loaded.'},{status:409});items=samples().map(validate);label='Sample portfolio loaded';}
 else if(input.op==='save'){items=[validate(input.record)];label=items[0].id?'Record updated':'Record created';const current=existing.find(r=>r.id===items[0].id);if(items[0].id&&!current)return Response.json({error:'This record no longer exists. Reload before editing.'},{status:409});if(current&&(current.updated!==items[0].updated||current.kind!==items[0].kind||current.demo!==items[0].demo))return Response.json({error:'This record changed. Close the form, reload, and try again.'},{status:409});}
 else if(input.op==='import'){if(!Array.isArray(input.records)||input.records.length<1||input.records.length>100)throw Error('Import 1–100 records in a records array.');const mapping=new Map<string,string>();for(const r of input.records){if(r.id){if(mapping.has(r.id))throw Error('Duplicate IDs in import.');mapping.set(r.id,crypto.randomUUID())}}items=input.records.map((v:any)=>{const r=validate({...v,id:v.id||'',demo:input.demo});return {...r,id:mapping.get(r.id)||crypto.randomUUID(),grant:r.grant?(mapping.get(r.grant)||r.grant):'',updated:''}});const keys=new Set<string>();for(const r of items){const key=r.kind+'|'+r.title.toLowerCase()+'|'+r.source;if(keys.has(key)||existing.some(e=>e.demo===r.demo&&e.kind===r.kind&&e.title.toLowerCase()===r.title.toLowerCase()&&e.source===r.source))throw Error('A matching record is already present: '+r.title);keys.add(key)}label='Records imported';}
 else throw Error('Unknown operation.');
 const now=new Date().toISOString();items=items.map(r=>({...r,id:r.id||crypto.randomUUID(),updated:now}));const all=[...items,...existing];for(const r of items){if(r.grant&&!all.some(g=>g.id===r.grant&&g.kind==='grant'&&g.demo===r.demo))throw Error('Linked grant must exist in the same workspace.');if(r.kind==='grant'&&r.grant)throw Error('Awards cannot be linked to another award.');}
 const isUpdate=input.op==='save'&&!!input.record.id;
 const statements=items.map(r=>isUpdate?db.prepare('UPDATE records SET payload=?,updated=? WHERE id=? AND updated=?').bind(JSON.stringify(r),r.updated,r.id,input.record.updated):db.prepare('INSERT INTO records (id,kind,payload,updated) VALUES (?,?,?,?)').bind(r.id,r.kind,JSON.stringify(r),r.updated));
 statements.push(db.prepare(isUpdate?'INSERT INTO activity (id,action,title,at) SELECT ?,?,?,? WHERE changes() > 0':'INSERT INTO activity (id,action,title,at) VALUES (?,?,?,?)').bind(crypto.randomUUID(),label,items.length===1?items[0].title:items.length+' records',now));const results=await db.batch(statements);if(isUpdate&&results[0].meta.changes===0)return Response.json({error:'This record changed while saving. Reload and try again.'},{status:409});return Response.json({ok:true,count:items.length});
 }catch(e){console.error(e);const msg=e instanceof Error?e.message:'';const storage=/D1|SQLITE|database|binding|store/i.test(msg);return Response.json({error:storage?'Saving is temporarily unavailable. Your input has not been cleared.':msg||'Unable to save record.'},{status:storage?503:400})}}
